name: Deploy to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runs on Linux

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up PowerShell
      uses: azure/powershell@v1
      with:
        azPSVersion: "latest"

    - name: Log in to Azure
      env:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      run: |
        az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
        az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Run deploy script
      shell: pwsh
      run: |
        pwsh ./deploy.ps1 -TenantId $env:AZURE_TENANT_ID -subscriptionId $env:AZURE_SUBSCRIPTION_ID
      env:
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
