name: Deploy to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runs on Linux

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Azure Az Module
      shell: pwsh
      run: |
        Install-Module -Name Az -Force -AllowClobber -Scope CurrentUser
        Import-Module Az
        # Verify installation
        Get-Module -ListAvailable -Name Az

    - name: Log in to Azure CLI
      env:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      run: |
        az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
        az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Log in to Azure PowerShell
      shell: pwsh
      env:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      run: |
        $securePassword = ConvertTo-SecureString $env:AZURE_CLIENT_SECRET -AsPlainText -Force
        $credential = New-Object PSCredential($env:AZURE_CLIENT_ID, $securePassword)
        Connect-AzAccount -ServicePrincipal -TenantId $env:AZURE_TENANT_ID -Credential $credential
        Set-AzContext -TenantId $env:AZURE_TENANT_ID -SubscriptionId $env:AZURE_SUBSCRIPTION_ID

    - name: Set Object ID from Secret
      run: |
        echo "OBJID=${{ secrets.AZURE_OBJECT_ID }}" >> $GITHUB_ENV

    - name: Deploy Bicep Template
      shell: pwsh
      env:
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        OBJID: ${{ env.OBJID }}
      run: |
        New-AzDeployment -Location "westeurope" `
          -TemplateFile "./main.bicep" `
          -Name "MyDeployment" `
          -TemplateParameterObject @{
              location = "westeurope"
              rgName = "cka-lab"
              key_vault_name = "cka-lab-kv1"
              VNetName = "cka-lab-VNet"
              SubNetName = "cka-lab-Subnet"
              objid = $env:OBJID
              vmSize = "Standard_B2ms"
          }
